assertNoLeakedSecrets: false   # les secret sont chiffrés par helm

persistence:
  enabled: false
  type: pvc
  storageClassName: azurefile-csi
  size: 10Gi

replicas: 1

initChownData: 
  enabled: false

datasources:
    datasources.yaml:
        apiVersion: 1
        datasources:
            - name: prometheus
              type: prometheus
              url: http://prometheus-server:9090
              isDefault: true
              timeInterval: 2m
grafana.ini:
  server:
    root_url: "https://%(domain)s/"
    domain: grafana.areaute2024.ovh
  users:
    allow_sign_up: false
    auto_assign_org: true
    auto_assign_org_role: Editor
    skip_org_role_sync: true

deploymentStrategy:
  type: Recreate

resources:
  requests: 
    cpu: 100m
    memory: 192Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  port: 3000

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "grafana-dashboards-kubernetes"
        orgId: 1
        folder: "Kubernetes"
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
      - name: "jenkins"
        orgId: 1
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/jenkins
      - name: "Kubernetes Overview"
        orgId: 1
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/k8s-overview


dashboards:
  grafana-dashboards-kubernetes:
    k8s-system-api-server:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
      token: ""
      datasource: prometheus
    k8s-system-coredns:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
      token: ""
      datasource: prometheus
    k8s-views-global:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
      token: ""
      datasource: prometheus
    k8s-views-namespaces:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
      token: ""
      datasource: prometheus
    k8s-views-nodes:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
      token: ""
      datasource: prometheus
    k8s-views-pods:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
      token: ""
      datasource: prometheus
  k8s-overview:
    k8s-overview:
      gnetId: 15661
      revision: 2
      datasource: prometheus
