repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus/prometheus
    version: 27.11.0
    values:
      - ./prometheus.values.yaml
    atomic: true

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 8.12.1
    values:
      - ./grafana.values.yaml
    atomic: true
